version: '3.7'
services:
    app:
        container_name: gauss-docker-java-app
        build: app

    nginx:
        container_name: nginxserver
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
